### ISSUE TITLE
期望作者大大增加一个等级榜

### ISSUE THREAD

**Issue by longyong** [Twiyin0/koishi-plugin-bella-sign-in#2]
1.期望增加等级榜，旁边显示积分，能更好的激发抽奖欲望（杂鱼~杂鱼~）
2.增加花双倍或多倍积分买减少别人积分（如花1000积分减少指定id 500或随机积分）

**Comment by Twiyin0** [comment]
感谢建议  
1. 等级榜可以制作，有空会安排上；  
2. 这个与我制作插件的理念相悖，所以不考虑

**Comment by Twiyin0** [comment]
积分榜已上线，请更新至v2.0.0以上
