### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by ling-shi-cyber** [Twiyin0/koishi-plugin-bella-sign-in#6]
[贝拉签到]>>  [bella-sign-in Error]:
                        Error: Protocol error: Connection closed.

**Comment by Twiyin0** [comment]
应该是文件没有写进去，可以再重试一下，不行的话只能重启puppeteer或者本插件

**Comment by Twiyin0** [comment]
你的环境是docker吗？

**Comment by ling-shi-cyber** [comment]
重装插件后解决了

**Comment by Twiyin0** [comment]
请提供详细的信息，插件是否可以正常使用，再此之前做了什么，你的期望是什么，你的环境是什么（docker，win还是linux），koishi版本、puppeteer版本。以便于分析问题以及解决办法。
从你提供的信息来看该报错不影响插件正常使用，如果你想屏蔽掉该报错可以打开koishi所在目录/node_modules/koishi-plugin-bella-sign-in/lib/index.js文件内1034行至1036行
![image](https://github.com/user-attachments/assets/3ac3417c-1301-4b02-81a7-b7980ea2544f)
